catalog:
  '@astrojs/db': ^0.12.0 
  '@astrojs/markdown-remark': ^5.2.0
  '@astrojs/rss': ^4.0.7
  '@astrojs/check': ^0.8.2
  '@astrojs/tailwind': ^5.1.0
  '@astrojs/starlight': ^0.25.1
  '@astrojs/web-vitals': ^1.0.0
  '@astrojs/node': ^8.3.2
  '@astrojs/cloudflare': ^11.0.1
  '@types/node': ^20.14.11
  astro: ^4.12.2
  astro-integration-kit: ^0.16.0
  astro-theme-provider: ^0.6.1
  typescript: ^5.5.4
  vite: ^5.3.4
  sharp: ^0.33.4

catalogs:
  min:
    astro: ^4.12
    '@astrojs/db': ^0.12
    astro-integration-kit: ^0.16
    vite: ^4 || ^5
  landing:
    motion: ^10.18.0
    powerglitch: ^2.3.3
    tailwindcss: ^3.4.4
    tailwind-merge: ^2.3.0
    tailwind-scrollbar: ^3.1.0
    astro-font: ^0.0.81
    astro-icon: ^1.1.0
    astro-seo: ^0.8.4
  docs:
    '@shoelace-style/shoelace': ^2.15.1
    astro-embed: ^0.7.2
    starlight-links-validator: ^0.9.1
    starlight-package-managers: ^0.6.0
    starlight-typedoc: ^0.13.0
    typedoc: ^0.26.4
    typedoc-plugin-markdown: ^4.2.1
  studiocms:
    '@iconify/types': ^2.0.0
    '@cloudinary/url-gen': ^1.19.0
    '@iconify-json/mdi': ^1.1.67
    '@iconify-json/logos': ^1.1.43
    '@iconify/utils': ^2.1.25
    '@inox-tools/sitemap-ext': ^0.3.1
    '@inox-tools/runtime-logger': ^0.3.0
    '@matthiesenxyz/astrolace': ^0.2.0
    '@matthiesenxyz/unocss-preset-daisyui': ^0.1.1
    '@markdoc/markdoc': ^0.4.0
    '@noble/hashes': ^1.4.0
    '@shikijs/transformers': ^1.10.3
    '@shoelace-style/shoelace': ^2.15.1
    '@types/micromatch': ^4.0.9
    '@unocss/astro': ^0.61.5
    '@unocss/reset': ^0.61.5
    unocss: ^0.61.5
    '@unpic/astro': ^0.0.46
    unpic: ^3.18.0
    arctic: ^1.9.1
    daisyui: ^4.12.10
    htmx.org: ^2.0.0
    lucia: ^3.2.0
    marked: ^13.0.2
    marked-alert: ^2.0.1
    marked-emoji: ^1.4.1
    marked-footnote: ^1.2.2
    marked-shiki: ^1.1.0
    marked-smartypants: ^1.1.7
    micromatch: ^4.0.7
    mrmime: ^2.0.0
    oslo: ^1.2.1
    shiki: ^1.10.3

packages:
  - "packages/*"
  - "playgrounds/*"
  - "www/*"