catalog:
  '@astrojs/db': ^0.14.2
  '@astrojs/markdown-remark': ^5.2.0
  '@astrojs/rss': ^4.0.7
  '@astrojs/check': ^0.9.4
  '@astrojs/tailwind': ^5.1.2
  '@astrojs/starlight': ^0.28.3
  '@astrojs/web-vitals': ^3.0.0
  '@astrojs/node': ^8.3.4
  '@types/node': ^20.14.11
  astro: ^4.16.6
  astro-integration-kit: ^0.16.1
  astro-theme-provider: ^0.6.1
  sharp: ^0.33.4
  typescript: ^5.6.3
  vite: ^5.4.8

catalogs:
  min:
    astro: ">=4.16"
    '@astrojs/db': ">=0.14.2"
    astro-integration-kit: ">=0.16"
    vite: ^4 || ^5
  landing:
    motion: ^10.18.0
    powerglitch: ^2.3.4
    tailwindcss: ^3.4.14
    tailwind-merge: ^2.5.4
    tailwind-scrollbar: ^3.1.0
    '@tailwindcss/typography': ^0.5.15
    astro-icon: ^1.1.1
    '@iconify-json/heroicons': ^1.2.0
  docs:
    "@11ty/eleventy-fetch": ^4.0.1
    "@lorenzo_lewis/starlight-utils": ^0.2.0
    "@types/hast": ^3.0.4
    astro-embed: ^0.7.4
    hast: ^1.0.0
    hast-util-select: ^6.0.3
    p-retry: ^6.2.0
    rehype: ^13.0.2
    starlight-versions: ^0.3.0
    starlight-package-managers: ^0.7.0
    starlight-typedoc: ^0.16.0
    typedoc: ^0.26.10
    typedoc-plugin-markdown: ^4.2.9
  studiocms:
    '@types/semver': ^7.5.8
    package-json: ^10.0.1
    semver: ^7.6.3
  studiocms-core:
    remark-rehype: ^11.1.0
    mdast-util-to-hast: ^13.2.0
  studiocms-shared:
    '@fontsource-variable/onest': 5.1.0
    '@inox-tools/runtime-logger': ^0.3.4
    '@iconify-json/heroicons': ^1.2.1
    "@matthiesenxyz/astrolace": ^0.3.2
    "@matthiesenxyz/astrodtsbuilder": ^0.1.2
    "@matthiesenxyz/integration-utils": ^0.2.0
    '@matthiesenxyz/unocss-preset-daisyui': ^0.1.2
    '@markdoc/markdoc': ^0.4.0
    '@noble/hashes': ^1.5.0
    '@unocss/astro': ^0.62.3
    '@unocss/reset': ^0.62.3
    '@types/micromatch': ^4.0.9
    "@astrojs/react": ^3.6.2
    "@types/react": ^18.3.5
    "@types/react-dom": ^18.3.0
    react: ^18.3.1
    react-dom: ^18.3.1
    unocss: ^0.62.3
    daisyui: ^4.12.10
    lucia: ^3.2.0
    arctic: ^1.9.1
    marked: ^13.0.2
    micromatch: ^4.0.8
    shiki: ^1.14.1
    unpic: ^3.18.0
    mrmime: ^2.0.0
    unified: ^11.0.5
  studiocms-renderer:
    '@shikijs/transformers': ^1.14.1
    "@mdx-js/mdx": ^3.0.1
    marked-alert: ^2.0.1
    marked-emoji: ^1.4.1
    marked-footnote: ^1.2.2
    marked-shiki: ^1.1.0
    marked-smartypants: ^1.1.7
    remark-gfm: ^4.0.0
    rehype-highlight: ^7.0.0
  studiocms-imagehandler:
    '@cloudinary/url-gen': ^1.21.0
    '@unpic/astro': ^0.0.47

packages:
  - "packages/*"
  - "playgrounds/*"
  - "www/*"
