import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
/**
 * Generate the `astroMarkdownConfig.d.ts` file
 */
export const rendererAstroMarkdownDTS = () => {
	const dtsFile = DTSBuilder();

	dtsFile.addSingleLineNote(
		'This file is generated by StudioCMS and should not be modified manually.'
	);

	dtsFile.addModule('studiocms:renderer/astroMarkdownConfig', {
		defaultExport: {
			typeDef: `import('astro').AstroConfig['markdown']`,
		},
	});

	const dtsText = dtsFile.makeAstroInjectedType('astroMarkdownConfig.d.ts');

	return dtsText;
};
