import { fileFactory } from '@matthiesenxyz/integration-utils/fileFactory';

/**
 * Generate the `renderer.d.ts` file
 */
export const rendererDTS = (rendererPath: string) => {
	const renderer = fileFactory();

	renderer.addLines('// This file is generated by StudioCMS\n\n');

	renderer.addLines(`declare module 'studiocms:renderer' {`);
	renderer.addLines(`
        /**
         * StudioCMS Content Renderer component
        */
        export const StudioCMSRenderer: typeof import('${rendererPath}').default;`);
	renderer.addLines('}');

	const rendererDTS = renderer.text();

	return rendererDTS;
};
