import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';

/**
 * Generate the `renderer.d.ts` file
 */
export const rendererDTS = (rendererPath: string) => {
	const dtsFile = DTSBuilder();

	dtsFile.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
	);

	dtsFile.addModule('studiocms:renderer', {
		namedExports: [
			{
				name: 'StudioCMSRenderer',
				multiLineDescription: ['# StudioCMS Content Renderer component'],
				typeDef: `typeof import('${rendererPath}').default`,
			},
		],
	});

	const dtsText = dtsFile.makeAstroInjectedType('renderer.d.ts');

	return dtsText;
};
