import { fileFactory } from '@matthiesenxyz/integration-utils/fileFactory';

/**
 * Generate the `astroMarkdownConfig.d.ts` file
 */
export const rendererAstroMarkdownDTS = () => {
	const renderer = fileFactory();

	renderer.addLines('// This file is generated by StudioCMS\n\n');

	renderer.addLines(`declare module 'studiocms:renderer/astroMarkdownConfig' {`);
	renderer.addLines(`const Config: import('astro').AstroConfig['markdown'];`);
	renderer.addLines('export default Config;');
	renderer.addLines('}');

	const rendererDTS = renderer.text();

	return rendererDTS;
};
