import { fileFactory } from '@matthiesenxyz/integration-utils/fileFactory';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

export const rendererConfigDTS = () => {
	const renderer = fileFactory();

	renderer.addLines('// This file is generated by StudioCMS\n\n');

	renderer.addLines(`declare module 'studiocms:renderer/config' {`);
	renderer.addLines(`const Config: import('${resolve('../index')}').StudioCMSRendererConfig;`);
	renderer.addLines('export default Config;');
	renderer.addLines('}');

	const rendererDTS = renderer.text();

	return rendererDTS;
};
