FROM mcr.microsoft.com/devcontainers/typescript-node:dev-22-bookworm@sha256:75328815541114f1b467fe727a5573bfcfbb1546728ab0c2b855b9a5155c1c07

# Copy welcome message
COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt
