import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';

const authConfig = DTSBuilder();

authConfig.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

authConfig.addModule('studiocms:auth/config', {
	defaultExport: {
		singleLineDescription: 'Auth Security Config for Username and Password Authentication.',
		typeDef: `{
		salt: string | Uint8Array;
		opts: {
			N: number;
			r: number;
			p: number;
			dkLen?: number;
			asyncTick?: number;
			maxmem?: number;
			onProgress?: (progress: number) => void;
		};
	}`,
	},
});

const dtsFile = authConfig.makeAstroInjectedType('auth-config.d.ts');

export default dtsFile;
