import fileFactory from '@matthiesenxyz/integration-utils/fileFactory';

const authConfigDTS = fileFactory();

authConfigDTS.addLines('// This file is generated by StudioCMS\n\n');

authConfigDTS.addLines(`declare module 'studiocms:auth/config' {`);
authConfigDTS.addLines(
	`	const AuthSecurityConfig: import('@studiocms/core').usernameAndPasswordConfig;`
);
authConfigDTS.addLines('	export default AuthSecurityConfig;');
authConfigDTS.addLines('}');

const DTSFile = authConfigDTS.text();

export default DTSFile;
