name: Write coauthors to a pull request
permissions:
  pull-requests: write
  
on:
  issue_comment:
    types:
      - created
      
jobs:
  generate-coauthors:
    name: Generate Coauthor
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: kevinzunigacuellar/coauthor-action@292b32bdbffc663431a2a37b3bfa597d83a74905 # v0.1.3