name: 'Format Code'

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Tools & Dependencies
        uses: ./.github/actions/install
      - name: Format code
        run: pnpm run lint:fix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[ci] lint'
          branch: ${{ github.head_ref }}
          commit_user_name: astrolicious
          commit_user_email: noreply@studiocms.xyz
